#:schema https://mise.jdx.dev/schema/mise.plugin.json

[exec-env]
cache-key = [
  """
  {% set option = opts.flake_nix | default(value='flake.nix') %}
  {% set path = [project_root, option] | join_path %}
  {% if path is exists %}{{ path | hash_file }}{% endif %}
  """,
  """
  {% set option = opts.flake_lock | default(value='flake.lock') %}
  {% set path = [project_root, option] | join_path %}
  {% if path is exists %}{{ path | hash_file }}{% endif %}
  """,
  """
  {% set option = opts.installable | default(value='.') %}
  {{ option }}
  """,
]
