#:schema https://mise.jdx.dev/schema/mise.plugin.json

[exec-env]
cache-key = [
  """
  {% if opts.flake_nix %}
    {{ opts.flake_nix }}
  {% endif %}
  """,
  """
  {{ [project_root] | concat(with=(opts.flake_nix | default(value='flake.nix'))) | join_path | hash_file }}
  """,
  """
  {% if opts.flake_lock %}
    {{ opts.flake_lock }}
  {% endif %}
  """,
  """
  {{ [project_root] | concat(with=(opts.flake_lock | default(value='flake.lock'))) | join_path | hash_file }}
  """,
]
